apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: model-llama3-8b
  namespace: llm-demo
spec:
  model:
    uri: hf://microsoft/Phi-3-mini-4k-instruct
    name: microsoft/Phi-3-mini-4k-instruct
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: router-managed
  namespace: llm-demo
spec:
  router:
    gateway: {}
    route: {}
    scheduler: {}
---
apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceServiceConfig
metadata:
  name: workload-single-gpu
  namespace: llm-demo
spec:
  replicas: 1
  template:
    containers:
    - name: main
      image: vllm/vllm-openai:latest
      resources:
        requests:
          nvidia.com/gpu: "1"
          cpu: "2"
          memory: 12Gi
        limits:
          nvidia.com/gpu: "1"
          cpu: "4"
          memory: 16Gi
